### ISSUE TITLE
audio/augmentation.py

### ISSUE THREAD

**Issue by PabloOrtizCabello** [danspeech/danspeech_training#5]
In line 40 there is a typo, I think it should read:

`scheme = self.choose_augmentation_scheme(self.augmentations_list)
`
However, after correcting it, I get still the following error:

`TypeError: choose_augmentation_scheme() takes 1 positional argument but 2 were given`

Any idea how to fix this? Thanks in advance!

**Comment by nc-rafj** [comment]
Will look at it later today. 

Did you correct to 
```python 
scheme = self.choose_augmentation_scheme()
```
?

Because I think that should work. :)

**Comment by PabloOrtizCabello** [comment]
Thanks for the quick answer! I changed that and I see now in line 44:

```
augmentor = getattr(self, augmentation)
TypeError: getattr(): attribute name must be string
```

I will try and follow the white rabbit

**Comment by nc-rafj** [comment]
Not sure why the getattr is there in the first place. It is definetly wrong.

I think I wrote the original code as follows:

```python
            scheme = self.choose_augmentation_scheme()
            # Apply the chosen augmentations
            for augmentation_function in scheme:
                recording = augmentation_function(recording, self.sampling_rate)
```

Does that work?

**Comment by PabloOrtizCabello** [comment]
That seems to work :) I get other errors passed that point, but that's another matter I have to investigate. Those changes in the augmentation script come from a commit from last month, not sure what the purpose was. Thanks!

**Comment by nc-rafj** [comment]
Yea, I think the changes stem from fixing the augmentation-scheme so that all "paths" are equally likely to happen. Unfortunately it also broke the functionality. Good luck. :)
